apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
spec:
  selector:
    matchLabels:
      app: udacitycapstone
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: udacitycapstone
    spec:
      containers:
      - name: udacitycapstone
        image: sonkumar0895/udacitycapstone:latest
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstone
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP