apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udacitycapstonedeployment
spec:
  selector:
    matchLabels:
      app: udacitycapstone
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: udacitycapstone
    spec:
      containers:
      - name: udacitycapstone
        image: sonkumar0895/udacitycapstone:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacitycapstonedeployment
  labels:
    app: udacitycapstonedeployment
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstonedeployment
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP